### PR TITLE
Remove superfluous slash in Persistence Class path

### LINKED ISSUE #354: set 'keep' for Configuration/Extbase/Persistence/Classes.php didn't get respected
**Describe the bug**
I've configured that the ExtBuilder didnt overrwrite my Classes.php but he still do.
```yaml
overwriteSettings:
  Configuration:
    #TCA merge not possible - use overrides directory
    TypoScript: merge
    Extbase:
      Persistence:
        Classes.php: keep
```
**To Reproduce**
1. Set overwriteSettings
2. Create file Configuration/Extbase/Persistence/Classes.php
3. Create an Entity which use \TYPO3\CMS\Extbase\Domain\Model\FrontendUser as Extended Model
4. Generate and see that it gets overridden

**Expected behavior**
Classes.php should not be changed

**TYPO3 Version**
10.4.12

**Extension Builder Version:**
Git-branch v10 compatibility

**Additional context**

### PR DESCRIPTION
**Pull request by nicodh**
Use constants for overwrite settings

Resolves #354

### CODE REVIEW

File: Classes/Service/FileGenerator.php [hunk 1]
```diff
@@ -27,6 +27,10 @@
 use TYPO3\CMS\Core\Utility\GeneralUtility;
 use TYPO3\CMS\Fluid\View\StandaloneView;
 
+const OVERWRITE_SETTING_SKIP = 1;
+const OVERWRITE_SETTING_KEEP = 1;
+const OVERWRITE_SETTING_MERGE = 1;
```
Comment (liayn) [inline Classes/Service/FileGenerator.php:32]: these constants are unused, right?

Comment (nicodh) [reply Classes/Service/FileGenerator.php]: Yes - first started to add them there and forgot to remove again!

**Review by liayn — APPROVED** [review]
