### PR TITLE
[BUGFIX] Language file not merged

### LINKED ISSUE #565: locallang.xlf merge does not work
**Describe the bug**
When you add own labels into an xlf file and edit the extension with the extension_builder and save, the own labels are removed.
settings.yaml:
```
  Resources:
    Private:
      Language: merge
```

**To Reproduce**
1. Add one or more labels by hand to locallang.xlf in your extension
e.g.:
```
<trans-unit id="firstname" resname="firstname">
	<source>Firstname</source>
</trans-unit>
```
2. Set the Language folder to merge in your settings.yaml
3. Open your extension with the extension_builder again and save it
4. The own label is removed

**Expected behavior**
The own label should not be removed, as in earlier versions of the extension_builder.

**TYPO3 Version**
10.4.23

**Extension Builder Version:**
TER version 10.0.3

### PR DESCRIPTION
**Pull request by PKuhlmay**
The language files inside Resources/Private/Language were not merged, after saving the extension inside the extension builder. It happened because the suffix was added twice.

will fix #565

### CODE REVIEW

File: Classes/Service/FileGenerator.php [hunk 1]
```diff
@@ -1151,10 +1151,9 @@ protected function generateLocallangFileContent(string $fileNameSuffix = '', str
             if ($variableName === 'domainObject') {
                 $filenameToLookFor .= '_' . $variable->getDatabaseTableName();
             }
-            $existingFile = $filenameToLookFor . '.xlf';
 
-            if (@file_exists($existingFile)) {
-                $existingLabels = $this->localizationService->getLabelArrayFromFile($existingFile, 'default');
+            if (@file_exists($filenameToLookFor)) {
```
Comment (simonschaufi) [inline Classes/Service/FileGenerator.php:1155]: Just from looking, does the file have the .xlf ending? You removed line 1154, that's why.

Comment (PKuhlmay) [reply Classes/Service/FileGenerator.php:1155]: That's because the file ending is added twice. So the file is f.e. `locallang.xlf.xlf` when the code checks, if this file exists.
In line 1137 the filename suffix is added for the first time.
Bildschirmfoto 2022-09-21 um 08 31 50

Bildschirmfoto 2022-09-21 um 08 31 58


But i now see, that the error is still happening at other positions.

Bildschirmfoto 2022-09-21 um 08 34 08
